// AUTO-GENERATED by build-registry.js — do not edit.
// Regenerate with: node build-registry.js

import * as app_appStore from './appStore/main.js';
import * as app_browser from './browser/main.js';
import * as app_calculator from './calculator/main.js';
import * as app_calendar from './calendar/main.js';
import * as app_cellESheet from './cellESheet/main.js';
import * as app_clock from './clock/main.js';
import * as app_export from './export/main.js';
import * as app_fileExplorer from './fileExplorer/main.js';
import * as app_mediaPlayer from './mediaPlayer/main.js';
import * as app_musicSpark from './musicSpark/main.js';
import * as app_notepad from './notepad/main.js';
import * as app_paint from './paint/main.js';
import * as app_photos from './photos/main.js';
import * as app_sampleApp from './sampleApp/main.js';
import * as app_settings from './settings/main.js';
import * as app_sledgePoint from './sledgePoint/main.js';
import * as app_taskManager from './taskManager/main.js';
import * as app_terminal from './terminal/main.js';
import * as app_vscode from './vscode/main.js';
import * as app_words from './words/main.js';

const APP_MODULES = {
    "appStore": app_appStore.default || app_appStore,
    "browser": app_browser.default || app_browser,
    "calculator": app_calculator.default || app_calculator,
    "calendar": app_calendar.default || app_calendar,
    "cellESheet": app_cellESheet.default || app_cellESheet,
    "clock": app_clock.default || app_clock,
    "export": app_export.default || app_export,
    "fileExplorer": app_fileExplorer.default || app_fileExplorer,
    "mediaPlayer": app_mediaPlayer.default || app_mediaPlayer,
    "musicSpark": app_musicSpark.default || app_musicSpark,
    "notepad": app_notepad.default || app_notepad,
    "paint": app_paint.default || app_paint,
    "photos": app_photos.default || app_photos,
    "sampleApp": app_sampleApp.default || app_sampleApp,
    "settings": app_settings.default || app_settings,
    "sledgePoint": app_sledgePoint.default || app_sledgePoint,
    "taskManager": app_taskManager.default || app_taskManager,
    "terminal": app_terminal.default || app_terminal,
    "vscode": app_vscode.default || app_vscode,
    "words": app_words.default || app_words,
};

const APP_MANIFESTS = [
    {"id":"appStore","uuid":"958d006c-cd70-485d-9f09-b070dc378451","name":"Microsoft Store","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"browser","uuid":"29c57f74-d460-4297-a9ce-652fee2c792f","name":"Browser","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"calculator","uuid":"e0c7c96c-8fe4-44c4-9792-b7ef107bcd2d","name":"Calculator","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"calendar","uuid":"41735587-3354-46e3-b3c0-eb9b9557ecdc","name":"Calendar","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"cellESheet","uuid":"018c838d-7ccf-410f-979d-806142a0c2bb","name":"Cell ESheet","version":"1.0.0","distribution":"store","associations":["cesheet","celsheet","csv"],"store":{"developer":"Windows 12","category":"Productivity","rating":"4.5","reviews":"987","description":"A spreadsheet application with formulas, multi-sheet support, and a familiar ribbon UI. Create and manage your data with ease.","features":["Formula support (SUM, AVERAGE, MIN, MAX)","Multi-sheet workbooks","Ribbon-style toolbar","Cell references and range selection","Save/load from virtual filesystem"],"screenshots":[{"bg":"linear-gradient(135deg, #217346, #33a867)","text":"Spreadsheet Editor"},{"bg":"linear-gradient(135deg, #33a867, #217346)","text":"Formula Bar"}],"size":"4 MB","ageRating":"3+"}},
    {"id":"clock","uuid":"b0920f32-1bb7-4a1e-a8bf-6482b5abfd71","name":"Clock","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"export","uuid":"0e5fc68f-7379-4027-bb52-67ff7a23b4f2","name":"Ex/port","version":"1.0.0","distribution":"store","associations":[],"store":{"developer":"Windows 12","category":"Utilities","rating":"4.7","reviews":"892","description":"Import files from your device to the filesystem, or export files to download. Supports all file types with drag-and-drop functionality.","features":["Drag-and-drop import","File browser export","Multiple destination folders","File type detection","Batch operations"],"screenshots":[{"bg":"linear-gradient(135deg, #0078D4, #00BCF2)","text":"Import Files"},{"bg":"linear-gradient(135deg, #00BCF2, #0078D4)","text":"Export Files"}],"size":"1 MB","ageRating":"3+"}},
    {"id":"fileExplorer","uuid":"7547fd06-5d94-48c3-84bf-061f09a5a717","name":"File Explorer","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"mediaPlayer","uuid":"23917c1e-2117-4404-b620-82cedd12a70e","name":"Media Player","version":"1.0.0","distribution":"builtin","associations":["mp3","wav","ogg","oga","m4a","mp4","webm"]},
    {"id":"musicSpark","uuid":"3a17e9c1-d05a-4798-ad50-5b4d322f8293","name":"Music Spark","version":"1.0.0","distribution":"store","associations":["mspark"],"store":{"developer":"Windows 12","category":"Music & Audio","rating":"4.9","reviews":"3,412","description":"A full beat-making studio in the style of FL Studio. Step sequencer, piano roll with 808 bass, song arranger, mixer, FX rack, 4 drum kits, and WAV export.","features":["8-track step sequencer with per-step velocity","Piano roll: lead synth + glide 808 bass with note lengths","Song arranger with pattern chaining + full-song export","4 drum kits (Studio, TR-808, Lo-Fi, Acoustic)","FX rack: tempo echo, convolution reverb, filters","Mixer with mute/solo, BPM, swing, metronome","Presets, randomizer, pattern copy/paste/clone, .mspark projects"],"screenshots":[{"bg":"linear-gradient(135deg, #1DB954, #0b2e16)","text":"Step Sequencer"},{"bg":"linear-gradient(135deg, #0b2e16, #1DB954)","text":"Piano Roll + Mixer"}],"size":"3 MB","ageRating":"3+"}},
    {"id":"notepad","uuid":"7d1fd060-41db-47b6-ab6a-d307b0e3a130","name":"Notepad","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"paint","uuid":"5e32e6ab-113e-4041-9739-6b08ea85533e","name":"Paint","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"photos","uuid":"d747123a-6cae-4b35-a0da-123d300d9e20","name":"Photos","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"sampleApp","uuid":"6912d871-6e9f-4b34-a236-bc72d9abac5d","name":"Sample App","version":"1.0.0","distribution":"store","associations":[],"store":{"developer":"Windows 12","category":"Productivity","rating":"4.5","reviews":"1,234","description":"Interactive sample app that demonstrates full system installation, uninstallation, and launching. Perfect for testing the app ecosystem.","features":["Easy installation","Full system integration","Interactive UI","Settings persistence"],"screenshots":[{"bg":"linear-gradient(135deg, #6a11cb, #2575fc)","text":"Sample Interface"},{"bg":"linear-gradient(135deg, #2575fc, #6a11cb)","text":"Features"}],"size":"2 MB","ageRating":"3+"}},
    {"id":"settings","uuid":"260fcb62-19fe-45ad-9ba3-cfe3dbf91ebd","name":"Settings","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"sledgePoint","uuid":"b5b3c1dd-be43-4c3f-a136-74a9978078b6","name":"Sledge Point","version":"1.0.0","distribution":"store","associations":["sledge","sledgepoint"],"store":{"developer":"Windows 12","category":"Productivity","rating":"4.6","reviews":"2,180","description":"Create stunning presentations with Sledge Point. Features a ribbon UI, slide transitions, drawing tools, and export to HTML, PDF, and more.","features":["Ribbon-style toolbar","Slide transitions (fade, slide, zoom)","Text, shapes, images, and tables","Freehand drawing tools","Presentation mode with slideshow","Export to HTML, PDF, SVG, and JSON"],"screenshots":[{"bg":"linear-gradient(135deg, #D83B01, #ff6b35)","text":"Slide Editor"},{"bg":"linear-gradient(135deg, #ff6b35, #D83B01)","text":"Presentation Mode"}],"size":"3 MB","ageRating":"3+"}},
    {"id":"taskManager","uuid":"788ae49a-c9b9-40aa-b135-910a7753f41f","name":"Task Manager","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"terminal","uuid":"36af75b0-71fa-4447-ab76-ddfc61d35c21","name":"Terminal","version":"1.0.0","distribution":"builtin","associations":[]},
    {"id":"vscode","uuid":"0c03acaf-f006-4c90-8590-763a7cca643a","name":"Visual Studio Code","version":"1.0.0","distribution":"store","associations":[],"store":{"developer":"Microsoft Corporation","category":"Developer Tools","rating":"4.8","reviews":"12,543","description":"Code editing. Redefined. Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux.","features":["Integrated terminal","Syntax highlighting","File explorer","Extensions marketplace","Git integration"],"screenshots":[{"bg":"linear-gradient(135deg, #1e1e1e, #2d2d2d)","text":"Code Editor"},{"bg":"linear-gradient(135deg, #007ACC, #1e90ff)","text":"Integrated Terminal"}],"size":"95 MB","ageRating":"3+"}},
    {"id":"words","uuid":"4b2c391f-9c8b-4560-b461-cd7369c24763","name":"Words","version":"1.0.0","distribution":"store","associations":[],"store":{"developer":"Windows 12","category":"Productivity","rating":"4.7","reviews":"1,567","description":"A rich text word processor with formatting toolbar, tables, links, and print support. Create and edit documents with ease.","features":["Rich text formatting","Table creation and editing","Hyperlink support","Print and export","Formatting toolbar"],"screenshots":[{"bg":"linear-gradient(135deg, #3b82f6, #60a5fa)","text":"Document Editor"},{"bg":"linear-gradient(135deg, #60a5fa, #3b82f6)","text":"Formatting Tools"}],"size":"2 MB","ageRating":"3+"}},
];

export { APP_MODULES, APP_MANIFESTS };
